<script>
    import Password from '$lib/Password.svelte';
    import SolutionsGrid from '$lib/SolutionsGrid.svelte';
    import TitleSection from '$lib/TitleSection.svelte';
    import TextTitle from '$lib/TextTitle.svelte';
    import GraphicSingle from '$lib/GraphicSingle.svelte';
    import Footnote from '$lib/Footnote.svelte';
    import Footnotes from '$lib/Footnotes.svelte';
	import { createFootnoteStore } from '$lib/footnoteUtils';
    import { base } from '$app/paths';
    
    let { data } = $props();
    const Chapter = "Small businesses";

    let solutionsList = data.categorySolutions[Chapter]?.list ?? [];
    let provinceCounts = data.categorySolutions[Chapter]?.counts ?? {};
    
	const footnoteStore = createFootnoteStore();
	const { footnotes, addFootnote } = footnoteStore;

	const fns = [
        'Innovation, Science, and Economic Development Canada, <i>Key Small Business Statistics</i> (ISEDC: 2025), 6,<a href="https://ised-isde.canada.ca/site/sme-research-statistics/sites/default/files/documents/ksbs-2024-v1-en.pdf" target="_blank">URL</a>.',
        'ISEDC, <i>Key Small Business Statistics</i>, 5. ',
        'Statistics Canada, “Business Counts in Rural and Small Town Canada: Interactive Dashboard” (Government of Canada, last modified September 15, 2025), <a href="https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2024008-eng.htm" target="_blank">URL</a>. This figure is for 2025.',
        'Statistics Canada, “Employment for all employees by enterprise size, annual” (Government of Canada, March 27, 2025), <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410021501" target="_blank">URL</a>. This figure is for 2024, and excludes unclassified businesses.',
        'SEDC, <i>Key Small Business Statistics</i>, 7. This figure is for the period 2017–2021.',
        'Marwa Abdu, <i>A Portrait of Small Business in Canada: Adaption, Agility, All at Once</i> (Canadian Chamber of Commerce – Business Data Lab, 2024), Table 1. <a href="http://chamber.ca/wp-content/uploads/2024/01/StateOfSmallBusiness_EN_Final.pdf" target="_blank">URL</a>.',
        'Canadian Federation of Independent Business, <i>Succession Tsunami: Preparing for a Decade of Small Business Transitions in Canada</i> (CFIB, 2022), 2. <a href="https://www.cfib-fcei.ca/hubfs/research/reports/2022/2022-10-EN-Succession-Tsunami-Preparing-for-a-decade-of-small-business-transitions-in-Canada.pdf" target="_blank">URL</a>.',
        'Marwa Abdu, <i>Portrait of Small Business in Canada</i>, 18.',
        'Marwa Abdu, <i>Portrait of Small Business in Canada</i>.',
        'Organisation for Economic Co-operation and Development, <i>OECD Economic Surveys: Canada</i> 2025, no. 12, <a href="https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/05/oecd-economic-surveys-canada-2025_ee18a269/28f9e02c-en.pdf" target="_blank">URL</a>.',
        ' Toronto Association of Business Improvement Areas, “Benefits of a BIA” (2023). <a href="https://www.toronto-bia.com/whats-a-bia/benefits-of-a-bia/" target="_blank">URL</a>.',
    ];
</script>

<div>
    <Password/>
    <TitleSection Title={Chapter} {Chapter}/>
    <div class="body-text">
        <TextTitle title="The Challenge" chapter={Chapter}/>
        <div class="inline-images">
            
            <GraphicSingle standalone={false}
                svg720={`${base}/web-assets/small-businesses/small-businesses_size-stat.svg`}
            />
            <p>
                Over 98% of businesses in Canada are small businesses.<Footnote id={addFootnote(fns[0])}/> These enterprises are the backbone of Canada’s economy, driving local development, sustaining communities, and providing employment across urban, rural, and remote regions. A small business is defined as an enterprise with 1 to 99 paid employees,<Footnote id={addFootnote(fns[1])}/> but the majority of small businesses in Canada are micro-firms with four or fewer employees, often owner operated and deeply rooted in their communities. 
            </p>
        </div>
        <p>
            There are 1.34 million small businesses in Canada.<Footnote id={addFootnote(fns[2])}/> Small business employs 6.82 million people nationwide,<Footnote id={addFootnote(fns[3])}/> and it contributes about one-third of the GDP generated by the private sector.<Footnote id={addFootnote(fns[4])}/> While many of Canada’s small businesses are located in more populous provinces, per capita there are proportionately more in Yukon, Prince Edward Island, and Western Canada.<Footnote id={addFootnote(fns[5])}/> 
        </p>
        <p>
            In rural and remote areas, where access to services and employment may be limited, small businesses are especially vital to their communities. The closure of even one enterprise can have ripple effects such as reducing access to basic services and weakening social cohesion. 
        </p>
        <p>
            Canadian small businesses are currently facing unique challenges. The country’s aging population is driving a “succession tsunami,” with 76% of business owners planning to exit their businesses within 10 years – a potential exchange of $2 trillion in business assets over the next decade. Yet according to a 2022 survey by the Canadian Federation of Independent Business, only 9% of business owners have a formal succession plan in place.<Footnote id={addFootnote(fns[6])}/> Poorly managed transitions could lead to widespread closures – a blow to any community and one with a disproportionate impact on smaller communities where businesses serve as both economic anchors and cultural hubs.  
        </p>
        <GraphicSingle
            svg720={`${base}/web-assets/small-businesses/small-businesses_rural-urban-map.svg`}
        />
        <p>
            Small businesses today are also still recovering from the effects of the COVID-19 pandemic. Over 60% of firms experienced revenue declines in 2020, and small businesses were twice as likely as larger ones to report significant losses.<Footnote id={addFootnote(fns[7])}/> Many are still working to rebuild in the face of inflationary pressures, supply chain disruptions, and a significant economic slowdown with the possibility of a recession.<Footnote id={addFootnote(fns[8])}/> These challenges are especially evident in downtown cores, where shifting consumer habits, hybrid work patterns, and major infrastructure projects have reduced foot traffic and disrupted local commerce.  
        </p>
        <p>
            New businesses are in a particularly difficult situation, especially in smaller municipalities that are more geographically dispersed. Small, rural, and remote communities often lack a permanent, centralized hub for business support and delivery, leaving entrepreneurs without access to mentorship, financing, and professional networks. Younger, innovative firms looking to expand also often struggle to access the needed financing because of their limited tangible assets and management experience.<Footnote id={addFootnote(fns[9])}/> 
        </p>
        <GraphicSingle
            svg720={`${base}/web-assets/small-businesses/small-businesses_births-chart.svg`}
        />
        <p>
            To address these challenges, communities and organizations across Canada are implementing a range of innovative strategies. This chapter highlights several of these solutions: 
        </p>
        <ul>
            <li>
                Support for succession planning  
            </li>
            <li>
                Programs and incentives for revitalizing downtown cores 
            </li>
            <li>
                Entrepreneurship supports to help new and emerging businesses
            </li>
        </ul>
        <p>
            Initiatives that support succession planning keep vital local enterprises in operation, maintaining continuity of services, employment, and community identity. Mentorship, financing options, and specialized succession planning assistance can help businesses stay in their communities. 
        </p>
        <p>
            Revitalization efforts focus on sustaining downtown cores and commercial districts, often led by Business Improvement Areas (BIAs). BIAs promote and distinguish their districts as business and shopping destinations, and they play an essential role in supporting civic improvements.<Footnote id={addFootnote(fns[10])}/> Across Canada, BIAs provide an avenue for organizing and financing support programs, highlighting how coordinated long-term strategies strengthen the resilience of local businesses. 
        </p>
        <div class="inline-images end">
            <GraphicSingle standalone={false}
                svg720={`${base}/web-assets/small-businesses/small-businesses_BIAs-map.svg`}
            />
            <p>
                Entrepreneurship supports play a critical role in nurturing new and innovative businesses. Regional business hubs, incubators, and accelerator programs can help address barriers to long-term success by creating pipelines for innovation and fostering collaboration. These initiatives are particularly important in smaller or remote communities, where limited resources can make it challenging for entrepreneurs to thrive.  
            </p>
            <p>
                Small businesses turn ideas into realities. They make each of our communities unique. A key component of economic growth, they are also social hubs for many neighbourhoods. The initiatives featured in this chapter address the full life cycle of small business development – from preserving existing enterprises to revitalizing commercial districts and fostering the next generation of entrepreneurs. They are evidence that local organizations are at the forefront in supporting the enterprises that keep their communities running through creative, place-based strategies to sustain and revitalize urban centres, small towns, and rural communities alike. 
            </p>
        </div>
    </div>
    <SolutionsGrid {Chapter} {solutionsList} {provinceCounts}/>
	<Footnotes footnotes={footnotes} />
</div>

<style>

</style>